interface CharacterMessage {
  message: string;
  user: string;
}

export default [
  { message: "Pikachu, use Thunderbolt!", user: "ash_k" },
  { message: "I need more potions before the next battle.", user: "brock_b" },
  { message: "Look at all the Magikarp flopping around!", user: "misty_w" },
  { message: "I just caught a rare Gyarados!", user: "ash_k" },
  {
    message: "You should try using a Great Ball for that one.",
    user: "brock_b",
  },
  { message: "We’re almost to the Pokémon Center!", user: "misty_w" },
  { message: "Got a badge from the Pewter Gym!", user: "ash_k" },
  { message: "Charizard, Flamethrower!", user: "ash_k" },
  { message: "Time to teach my Pokémon some new moves.", user: "brock_b" },
  { message: "My Staryu is so sparkly!", user: "misty_w" },
  { message: "Is that a shiny Pokémon?!", user: "ash_k" },
  { message: "Don't forget to stock up on Revives.", user: "brock_b" },
  { message: "Water Pokémon are the best!", user: "misty_w" },
  { message: "Gotta catch 'em all!", user: "ash_k" },
  { message: "Geodude, use Rock Throw!", user: "brock_b" },
  { message: "Psyduck, what are you doing?", user: "misty_w" },
  { message: "Evolving my Eevee into a Vaporeon!", user: "ash_k" },
  { message: "Onix, Dig!", user: "brock_b" },
  { message: "Training my Pokémon in the Viridian Forest.", user: "ash_k" },
  { message: "Team Rocket's blasting off again!", user: "narrator" },
  { message: "Preparing for the Pokémon League!", user: "ash_k" },
  {
    message: "I'm going to become the very best Pokémon Breeder!",
    user: "brock_b",
  },
  { message: "Cerulean City Gym is the next challenge!", user: "misty_w" },
  { message: "Trading Pokémon with my friends!", user: "ash_k" },
  { message: "I wonder what's inside this Rare Candy?", user: "brock_b" },
  { message: "My Goldeen is so elegant!", user: "misty_w" },
  { message: "My Scyther is ready to slice and dice!", user: "guzma" },
  { message: "Plumeria, get those Grunts in line!", user: "guzma" },
  { message: "Alola! My name is Lillie, nice to meet you!", user: "lillie" },
  { message: "Nebby, get back in the bag!", user: "lillie" },
  { message: "I'm researching the Ultra Dimensions.", user: "lillie" },
  { message: "Did someone say malasadas?", user: "hau" },
  { message: "My Rowlet is taking a nap.", user: "hau" },
  { message: "I'm training to be the Island Kahuna!", user: "hau" },
  { message: "Gladion... where are you going?", user: "lillie" },
  { message: "Silvally, use Multi-Attack!", user: "gladion" },
  { message: "I don't need anyone's help.", user: "gladion" },
  { message: "Type: Null is my partner.", user: "gladion" },
  { message: "Wicke! More potions, please!", user: "guzma" },
  { message: "Don't worry, everyone. I'll heal your Pokémon.", user: "wicke" },
  {
    message: "Aether Foundation is dedicated to Pokémon conservation.",
    user: "wicke",
  },
  { message: "My Decidueye is ready for battle!", user: "rowlet_trainer" },
  { message: "Primarina's song is so beautiful!", user: "primarina_fan" },
  { message: "Mightyena, use Crunch!", user: "maxie" },
  {
    message: "Expanding the landmass is essential for Pokémon prosperity!",
    user: "maxie",
  },
  { message: "Groudon, awaken!", user: "maxie" },
  { message: "Sharpedo, use Aqua Jet!", user: "archie" },
  {
    message: "Expanding the sea will create a paradise for Water Pokémon!",
    user: "archie",
  },
  { message: "Kyogre, arise!", user: "archie" },
  { message: "My Mudkip is evolving!", user: "may" },
  { message: "Contests are so much fun!", user: "may" },
  { message: "Beautifly, use Silver Wind!", user: "may" },
  { message: "My Blaziken is unstoppable!", user: "brendan" },
  { message: "I'm challenging the Elite Four!", user: "brendan" },
  { message: "Sceptile, use Leaf Blade!", user: "brendan" },
  { message: "Wally's gotten so strong!", user: "brendan" },
  { message: "My Gardevoir is my best friend.", user: "wally" },
  { message: "I'm feeling much better now.", user: "wally" },
  { message: "Steven... is so cool.", user: "wally" },
  { message: "My Metagross is a marvel of steel.", user: "steven" },
  { message: "The balance of nature must be preserved.", user: "steven" },
  { message: "Do you appreciate the beauty of rare stones?", user: "steven" },
  { message: "Salamence, use Fly!", user: "drake" },
  { message: "My Pokémon are burning with passion!", user: "flannery" },
  { message: "Glacia, you're going down!", user: "flannery" },
  { message: "Zekrom, strike them down!", user: "hilda" },
  { message: "Truth and ideals... what do they really mean?", user: "n" },
  { message: "Pokémon are not tools to be used!", user: "n" },
  { message: "My Zorua is quite mischievous.", user: "n" },
  { message: "Cheren, I'm going to beat you this time!", user: "hilbert" },
  { message: "Bianca, are you okay?", user: "hilda" },
  { message: "My Munna evolved into Musharna!", user: "bianca" },
  {
    message: "I'm still learning, but I'll become a great trainer!",
    user: "bianca",
  },
  { message: "My Serperior is so graceful.", user: "hilda" },
  { message: "Emboar, use Flame Charge!", user: "hilbert" },
  {
    message: "I'm studying to become a Pokémon Professor like my dad.",
    user: "cheren",
  },
  { message: "My Liepard is ready for battle.", user: "cheren" },
  { message: "Plasma grunts, attack!", user: "ghetsis" },
  { message: "The world will be mine!", user: "ghetsis" },
  { message: "My Hydreigon is a force to be reckoned with.", user: "ghetsis" },
  { message: "Elesa's Emolga are so cute!", user: "elesa_fan" },
  { message: "Clay's Excadrill is tough!", user: "clay_challenger" },
  { message: "Working hard at the Pokémon Musical!", user: "rosa" },
  { message: "My Riolu is evolving!", user: "nate" },
  { message: "My Swampert can handle anything!", user: "mudkip_master" },
  { message: "I'm training my Pokémon on Mt. Pyre.", user: "mt_pyre_trainer" },
  { message: "Trying to catch a Feebas in Mt. Pyre.", user: "feebas_hunter" },
  { message: "Trying to catch a shiny on Mt. Pyre.", user: "shiny_hunter" },
  { message: "My Milotic is so beautiful!", user: "milotic_lover" },
  { message: "Exploring the underwater caves is so cool!", user: "cave_diver" },
  {
    message: "Watch out for the currents in Sootopolis City!",
    user: "sootopolis_citizen",
  },
  {
    message: "I'm going to win the Hoenn Grand Festival!",
    user: "contest_star",
  },
  {
    message: "My Pokémon's coolness is off the charts!",
    user: "coolness_trainer",
  },
  { message: "Gotta get those ribbons!", user: "ribbon_master" },
  { message: "Double battles are my specialty!", user: "double_battle_pro" },
  { message: "Roaming Pokémon are so hard to find!", user: "roamer_hunter" },
  { message: "Finally caught Latias!", user: "latias_catcher" },
  { message: "Finally caught Latios! I hate roamers!", user: "latios_catcher" },
  { message: "My Rayquaza is so powerful!", user: "rayquaza_trainer" },
  {
    message: "Team Aqua/Magma won't get away with this!",
    user: "team_aqua_magma_fighter",
  },
  { message: "The Safari Zone is so much fun!", user: "safari_zone_fan" },
  {
    message: "Trying to get a high score in the Trick House.",
    user: "trick_house_master",
  },
  {
    message: "Battling Winona's flying types is a challenge!",
    user: "winona_challenger",
  },
  {
    message: "Tate and Liza's psychic Pokémon are tough!",
    user: "tate_and_liza_challenger",
  },
  { message: "Norman's Slaking is so strong!", user: "norman_challenger" },
  { message: "My Pokémon are as cold as ice!", user: "glacia" },
  { message: "Feel the power of my psychic Pokémon!", user: "drake" },
  { message: "I will become the Champion!", user: "brendan" },
  { message: "I'll win the next Grand Festival!", user: "may" },
  { message: "Groudon, awaken!", user: "maxie" },
  { message: "Expanding landmass is vital!", user: "maxie" },
  { message: "The power of the sea is limitless!", user: "archie" },
  { message: "I'll crush you!", user: "maxie" },
  { message: "My Infernape is blazing!", user: "lucas" },
  { message: "Let's go, Piplup!", user: "dawn" },
  { message: "I'll be the top Coordinator!", user: "dawn" },
  { message: "Dialga, roar!", user: "cyrus" },
  { message: "Emotions are meaningless.", user: "cyrus" },
  { message: "I'll create a perfect world!", user: "cyrus" },
  { message: "My Luxray can see through anything!", user: "lucas" },
  { message: "Palkia, distort space!", user: "cyrus" },
  { message: "Time and space are mine to control!", user: "cyrus" },
  { message: "I believe in my Pokémon!", user: "lucas" },
  { message: "Buneary, use Dizzy Punch!", user: "dawn" },
  { message: "My Empoleon is so elegant!", user: "dawn" },
  { message: "Cynthia is so strong...", user: "dawn" },
  { message: "My Garchomp is unbeatable!", user: "cynthia" },
  { message: "Let's see what you're made of.", user: "cynthia" },
  { message: "My Snivy is so cool!", user: "hilda" },
  { message: "Tepig, use Ember!", user: "hilbert" },
  { message: "Oshawott, use Water Gun!", user: "hilda" },
  { message: "I'll be the very best!", user: "hilbert" },
  { message: "Reshiram, lend me your power!", user: "hilbert" },
  { message: "Zekrom, strike them down!", user: "hilda" },
  { message: "Truth will prevail!", user: "hilbert" },
  { message: "Ideals give us strength!", user: "hilda" },
  { message: "N, I'll stop you!", user: "hilbert" },
  { message: "Pokémon are not tools!", user: "N" },
  { message: "I understand Pokémon.", user: "N" },
  { message: "Let Pokémon be free!", user: "N" },
  { message: "My Samurott is powerful!", user: "hilda" },
  { message: "Emboar, use Flamethrower!", user: "hilbert" },
  { message: "Serperior, use Leaf Storm!", user: "hilda" },
  { message: "Watch out for Winona's aerial aces!", user: "wallace" },
  { message: "My Altaria will soar to victory!", user: "winona" },
  { message: "I'm the master of Hoenn's skies!", user: "winona" },
  { message: "Dive deep into the ocean of my strategy!", user: "juan" },
  { message: "My Whiscash will swallow you whole!", user: "juan" },
  { message: "Feel the sting of my poison Pokémon!", user: "roark" },
  { message: "Cranidos, Head Smash!", user: "roark" },
  { message: "My Gardenia and I are blooming with power!", user: "gardenia" },
  { message: "Torterra, Earthquake!", user: "gardenia" },
  { message: "Maylene's fighting spirit burns bright!", user: "maylene" },
  { message: "Lucario, Aura Sphere!", user: "maylene" },
  {
    message: "Wake up and smell the coffee, it's battle time!",
    user: "crasher wake",
  },
  { message: "Floatzel, Aqua Jet!", user: "crasher wake" },
  { message: "Fantina's ghostly presence is unnerving!", user: "fantina" },
  { message: "Drifblim, Shadow Ball!", user: "fantina" },
  { message: "Byron's steely resolve is unshakeable!", user: "byron" },
  { message: "Bastiodon, Iron Head!", user: "byron" },
  { message: "Candice's icy demeanor hides a fiery passion!", user: "candice" },
  { message: "Abomasnow, Blizzard!", user: "candice" },
  {
    message: "Volkner's electrifying personality is shocking!",
    user: "volkner",
  },
  { message: "Electivire, Thunder!", user: "volkner" },
  {
    message: "My strategy is like a puzzle, can you solve it?",
    user: "grimsley",
  },
  { message: "Liepard, Night Slash!", user: "grimsley" },
  { message: "Caitlin's psychic powers are overwhelming!", user: "caitlin" },
  { message: "Reuniclus, Psychic!", user: "caitlin" },
  { message: "Marshal's fighting spirit is unmatched!", user: "marshal" },
  { message: "Conkeldurr, Mach Punch!", user: "marshal" },
  {
    message: "Shauntal's spooky stories will chill you to the bone!",
    user: "shauntal",
  },
  { message: "Chandelure, Flamethrower!", user: "shauntal" },
  { message: "Enjoy the dazzling display of my fireworks!", user: "marlon" },
  { message: "Jellicent, Water Spout!", user: "marlon" },
  { message: "Elesa's electrifying style is dazzling!", user: "elesa" },
  { message: "Emolga, Discharge!", user: "elesa" },
  { message: "Clay's down-to-earth attitude is refreshing!", user: "clay" },
  { message: "Excadrill, Earthquake!", user: "clay" },
  { message: "Skyla's aerial acrobatics are breathtaking!", user: "skyla" },
  { message: "Swoobat, Air Slash!", user: "skyla" },
  { message: "Brycen's icy exterior hides a warm heart!", user: "brycen" },
  { message: "Cryogonal, Ice Beam!", user: "brycen" },
  {
    message: "Drayden's wisdom is as ancient as his Pokémon!",
    user: "drayden",
  },
  { message: "Haxorus, Dragon Claw!", user: "drayden" },
  { message: "Iris's youthful energy is infectious!", user: "iris" },
  { message: "Haxorus, Outrage!", user: "iris" },
  { message: "My Pokémon and I share an unbreakable bond!", user: "N" },
  { message: "Zorua, Illusion!", user: "N" },
  { message: "Prepare to face the might of Team Plasma!", user: "ghetsis" },
  { message: "Hydreigon, Tri Attack!", user: "ghetsis" },
  { message: "My Hydreigon's power is unmatched!", user: "ghetsis" },
  { message: "I'll liberate all Pokémon!", user: "N" },
  { message: "Zekrom/Reshiram, Fusion Bolt/Flare!", user: "N" },
  { message: "My rock-solid defense is impenetrable!", user: "roark" },
  { message: "Feel the sting of my Toxic Spikes!", user: "falkner" },
  { message: "My Miltank is undefeated!", user: "whitney" },
  { message: "Prepare for a shocking defeat!", user: "watts" },
  {
    message: "The burning passion of my fire Pokémon will consume you!",
    user: "flannery",
  },
  {
    message: "My ice-cold strategy will freeze you in your tracks!",
    user: "glacia",
  },
  {
    message: "My psychic Pokémon see right through your tactics!",
    user: "sidney",
  },
  { message: "The might of my dragons is unstoppable!", user: "drake" },
  { message: "My fighting spirit will never waver!", user: "chuck" },
  {
    message: "My steel Pokémon are an impenetrable fortress!",
    user: "jasmine",
  },
  { message: "My bug Pokémon will swarm you!", user: "bugsy" },
  { message: "Prepare to be petrified by my ghost Pokémon!", user: "morty" },
  { message: "The dark depths of my strategy will engulf you!", user: "clair" },
  { message: "Go, Pidgey! I choose you!", user: "youngster" },
  {
    message: "My Rattata is in the top percentage of Rattata.",
    user: "youngster",
  },
  { message: "Bet you've never seen a Pokémon like this!", user: "lass" },
  { message: "My Pokémon are super cute and super strong!", user: "lass" },
  { message: "Time to show you what I've learned!", user: "school kid" },
  { message: "I've been training hard for this battle!", user: "hiker" },
  { message: "My Pokémon are tough as the mountains!", user: "hiker" },
  { message: "I'll fish you out of the competition!", user: "fisherman" },
  { message: "My Magikarp will evolve any day now!", user: "fisherman" },
  { message: "I'm the coolest trainer on this route!", user: "camper" },
  { message: "My Pokémon and I are best buds!", user: "picnicker" },
  { message: "Have a nice picnic... after I defeat you!", user: "picnicker" },
  { message: "My Pokémon are ready to rumble!", user: "biker" },
  { message: "Prepare for a high-speed battle!", user: "cyclist" },
  { message: "I'm delivering a crushing defeat!", user: "deliveryman" },
  { message: "My Pokémon are always stylishly prepared!", user: "beauty" },
  { message: "Don't underestimate my Pokémon's beauty!", user: "beauty" },
  { message: "My psychic powers are unmatched!", user: "psychic" },
  { message: "Prepare to be amazed by my magic!", user: "magician" },
  { message: "I'm the master of disguise!", user: "black belt" },
  { message: "My Pokémon are trained in the ancient arts!", user: "ninja boy" },
  { message: "My Pokémon are tougher than they look!", user: "bird keeper" },
  { message: "My team is a real hoot!", user: "bird keeper" },
  { message: "Prepare for a shocking defeat!", user: "guitarist" },
  { message: "My Pokémon rock!", user: "guitarist" },
  { message: "I'm going to paint you a picture of defeat!", user: "artist" },
  { message: "My Pokémon are true works of art!", user: "artist" },
  { message: "My Pokémon are as sweet as I am!", user: "kindler" },
  { message: "Don't underestimate my cuteness!", user: "kindler" },
  { message: "My Pokémon are stylish and strong!", user: "gentleman" },
  { message: "A true gentleman never loses!", user: "gentleman" },
  { message: "My Pokémon are just as elegant as I am!", user: "socialite" },
  { message: "Darling, prepare to be defeated!", user: "socialite" },
  { message: "I'm going to clean up the competition!", user: "janitor" },
  {
    message: "My Pokémon are sparkling clean and ready to battle!",
    user: "janitor",
  },
  { message: "I'm the ace of this route!", user: "pilot" },
  { message: "Prepare for takeoff!", user: "pilot" },
  { message: "I'm all fired up for this battle!", user: "firebreather" },
  { message: "My Pokémon are breathing fire!", user: "firebreather" },
  { message: "My Pokémon are as mysterious as I am!", user: "hex maniac" },
  { message: "You'll be cursed if you lose!", user: "hex maniac" },
  {
    message: "My Pokémon are trained in the art of illusion!",
    user: "stage magician",
  },
  { message: "Prepare to be amazed!", user: "stage magician" },
  { message: "I'm reporting for duty... and battle!", user: "officer" },
  { message: "My Pokémon uphold the law... of battle!", user: "officer" },
  { message: "I'm here to serve... a defeat!", user: "waiter" },
  { message: "My Pokémon are always ready to serve!", user: "waitress" },
  { message: "I'm baking up a storm of victory!", user: "chef" },
  {
    message: "My Pokémon are the best ingredients for a winning recipe!",
    user: "chef",
  },
  { message: "I'm digging up a victory!", user: "ruin maniac" },
  { message: "My Pokémon are ancient and powerful!", user: "ruin maniac" },
  {
    message: "My Pokémon are ready for battle, let's do this!",
    user: "trainer",
  },
  { message: "I'm going to be the best trainer ever!", user: "trainer" },
  { message: "I'm a real Pokémon master!", user: "trainer" },
  { message: "I'm always up for a challenge!", user: "trainer" },
  { message: "My Pokémon are stronger than yours!", user: "trainer" },
  { message: "I'm not afraid of a little competition!", user: "trainer" },
  { message: "I've been training hard, you're gonna lose!", user: "trainer" },
  { message: "I'm not afraid of anything!", user: "trainer" },
  {
    message:
      "I'm the best there is, the best there was, the best there ever will be!",
    user: "trainer",
  },
  {
    message: "Let's go, my Pokémon, show them what we're made of!",
    user: "trainer",
  },
  { message: "I'm on fire today!", user: "trainer" },
  { message: "I'm unstoppable!", user: "trainer" },
  { message: "This is going to be epic!", user: "trainer" },
  { message: "I'm ready for a good fight!", user: "trainer" },
  { message: "I'm going to win, no doubt about it!", user: "trainer" },
  { message: "This is the moment I've been training for!", user: "trainer" },
  { message: "I'm ready to battle!", user: "trainer" },
  { message: "I'm not going to go down without a fight!", user: "trainer" },
  { message: "You're going down!", user: "trainer" },
  { message: "My Pokémon are the best!", user: "trainer" },
  { message: "This is gonna be awesome!", user: "trainer" },
  { message: "I'm going to make you regret challenging me!", user: "trainer" },
  { message: "I'm not afraid of anything!", user: "trainer" },
  { message: "I'm the best!", user: "trainer" },
  { message: "This is my destiny!", user: "trainer" },
  { message: "I'm ready to unleash my power!", user: "trainer" },
  { message: "I'm going to take you down!", user: "trainer" },
  { message: "This is going to be fun!", user: "trainer" },
  { message: "My Pokémon and I are unstoppable!", user: "trainer" },
  { message: "I'm going to make you famous... as a loser!", user: "trainer" },
  { message: "This is my time to shine!", user: "trainer" },
  { message: "Prepare to be defeated!", user: "trainer" },
  { message: "I'm the champion, and I'm here to stay!", user: "champion" },
  { message: "I'm the strongest trainer in the region!", user: "champion" },
  { message: "I've been training hard to defend my title!", user: "champion" },
  { message: "I'm not going to give up my title easily!", user: "champion" },
  { message: "I'm always ready for a challenge!", user: "champion" },
  {
    message: "I'm the best there is, and I'm here to prove it!",
    user: "champion",
  },
  { message: "I'm the ultimate Pokémon master!", user: "champion" },
  { message: "I'm the strongest trainer alive!", user: "champion" },
  { message: "You'll need more than that to beat me!", user: "champion" },
  {
    message: "I'm the champion, and I'm not going anywhere!",
    user: "champion",
  },
  { message: "I'm ready to take on any challenger!", user: "champion" },
  { message: "I'm the champion, and I'm here to stay!", user: "champion" },
  {
    message: "I'm the best there is, and I'm here to prove it!",
    user: "champion",
  },
  { message: "I'm the ultimate Pokémon master!", user: "champion" },
  { message: "I'm the strongest trainer alive!", user: "champion" },
  { message: "You'll need more than that to beat me!", user: "champion" },
  {
    message: "I'm the champion, and I'm not going anywhere!",
    user: "champion",
  },
  { message: "I'm ready to take on any challenger!", user: "champion" },
  { message: "I'm the champion, and I'm here to stay!", user: "champion" },
  {
    message: "I'm the best there is, and I'm here to prove it!",
    user: "champion",
  },
  { message: "I'm the ultimate Pokémon master!", user: "champion" },
  { message: "I'm the strongest trainer alive!", user: "champion" },
  { message: "You'll need more than that to beat me!", user: "champion" },
  {
    message: "I'm the champion, and I'm not going anywhere!",
    user: "champion",
  },
  { message: "I'm ready to take on any challenger!", user: "champion" },
  { message: "I'm the champion, and I'm here to stay!", user: "champion" },
  {
    message: "I'm the best there is, and I'm here to prove it!",
    user: "champion",
  },
  { message: "I'm the ultimate Pokémon master!", user: "champion" },
  { message: "I'm the strongest trainer alive!", user: "champion" },
  { message: "You'll need more than that to beat me!", user: "champion" },
  {
    message: "I'm the champion, and I'm not going anywhere!",
    user: "champion",
  },
  { message: "I'm ready to take on any challenger!", user: "champion" },
  { message: "I'm the champion, and I'm here to stay!", user: "champion" },
  {
    message: "I'm the best there is, and I'm here to prove it!",
    user: "champion",
  },
  { message: "I'm the ultimate Pokémon master!", user: "champion" },
  { message: "I'm the strongest trainer alive!", user: "champion" },
  { message: "You'll need more than that to beat me!", user: "champion" },
  {
    message: "I'm the champion, and I'm not going anywhere!",
    user: "champion",
  },
  { message: "I'm ready to take on any challenger!", user: "champion" },
  { message: "I'm the champion, and I'm here to stay!", user: "champion" },
  {
    message: "I'm the best there is, and I'm here to prove it!",
    user: "champion",
  },
  { message: "I'm the ultimate Pokémon master!", user: "champion" },
  { message: "I'm the strongest trainer alive!", user: "champion" },
  { message: "You'll need more than that to beat me!", user: "champion" },
  {
    message: "I'm the champion, and I'm not going anywhere!",
    user: "champion",
  },
  { message: "I'm ready to take on any challenger!", user: "champion" },
  { message: "I'm the champion, and I'm here to stay!", user: "champion" },
  {
    message: "I'm the best there is, and I'm here to prove it!",
    user: "champion",
  },
  { message: "I'm the ultimate Pokémon master!", user: "champion" },
  { message: "I'm the strongest trainer alive!", user: "champion" },
  { message: "You'll need more than that to beat me!", user: "champion" },
  {
    message: "I'm the champion, and I'm not going anywhere!",
    user: "champion",
  },
  { message: "I'm ready to take on any challenger!", user: "champion" },
  { message: "I'm the champion, and I'm here to stay!", user: "champion" },
  {
    message: "I'm the best there is, and I'm here to prove it!",
    user: "champion",
  },
  { message: "I'm the ultimate Pokémon master!", user: "champion" },
  { message: "I'm the strongest trainer alive!", user: "champion" },
  { message: "You'll need more than that to beat me!", user: "champion" },
  {
    message: "I'm the champion, and I'm not going anywhere!",
    user: "champion",
  },
  { message: "I'm ready to take on any challenger!", user: "champion" },
  {
    message: "My team is built for competitive battling!",
    user: "competitive_trainer",
  },
  { message: "I'm breeding for perfect IVs!", user: "pokemon_breeder" },
  { message: "Shiny hunting is my passion!", user: "shiny_hunter_2" },
  {
    message: "I'm collecting all the Mega Stones!",
    user: "mega_stone_collector",
  },
  { message: "My living dex is almost complete!", user: "living_dex_builder" },
  {
    message: "I'm mastering all the different battle styles!",
    user: "battle_master",
  },
  {
    message: "I'm on a quest to become the strongest trainer!",
    user: "aspiring_champion",
  },
  { message: "I'm exploring every corner of the region!", user: "explorer" },
  {
    message: "I'm researching the mysteries of Pokémon evolution!",
    user: "pokemon_researcher",
  },
  {
    message: "I'm documenting all the different Pokémon species!",
    user: "pokemon_documentarian",
  },
  {
    message: "I'm training my Pokémon to be the best they can be!",
    user: "dedicated_trainer",
  },
  {
    message: "I'm always learning new strategies and techniques!",
    user: "strategic_trainer",
  },
  {
    message: "I'm building a team with perfect synergy!",
    user: "synergy_master",
  },
  {
    message: "I'm testing out different team compositions!",
    user: "team_builder",
  },
  {
    message: "I'm analyzing my opponents' weaknesses!",
    user: "analytical_trainer",
  },
  {
    message: "I'm predicting my opponents' next moves!",
    user: "predictive_trainer",
  },
  { message: "I'm adapting my strategy on the fly!", user: "adaptive_trainer" },
  { message: "I'm always pushing my limits!", user: "limit_pusher" },
  { message: "I'm never giving up!", user: "determined_trainer" },
  {
    message: "I'm going to become a Pokémon legend!",
    user: "legendary_trainer",
  },
  { message: "My Snivy is evolving!", user: "hilda" },
  { message: "Tepig, use Flame Charge!", user: "hilbert" },
  { message: "Oshawott, use Aqua Jet!", user: "hilda" },
  { message: "Training in Pinwheel Forest!", user: "hilbert" },
  { message: "Challenging the Striaton City Gym!", user: "hilda" },
  { message: "Exploring Nacrene City!", user: "hilbert" },
  { message: "My Pokémon are learning so many new moves!", user: "hilda" },
  { message: "Battling Team Plasma in Castelia City!", user: "hilbert" },
  { message: "Heading to Nimbasa City for the next Gym Badge!", user: "hilda" },
  { message: "Riding the Ferris wheel in Nimbasa City!", user: "hilbert" },
  { message: "Driftveil City Gym, here I come!", user: "hilda" },
  { message: "Exploring the Chargestone Cave!", user: "hilbert" },
  { message: "Mistralton City Gym is next!", user: "hilda" },
  { message: "Flying high above Unova!", user: "hilbert" },
  { message: "Icirrus City Gym, prepare for battle!", user: "hilda" },
  { message: "Training in the Dragonspiral Tower!", user: "hilbert" },
  { message: "Opelucid City Gym, let's do this!", user: "hilda" },
  {
    message: "Exploring the different seasons in Opelucid City!",
    user: "hilbert",
  },
  { message: "Humilau City Gym is my final challenge!", user: "hilda" },
  { message: "Surfing on the waves near Humilau City!", user: "hilbert" },
  { message: "Preparing for the Pokémon League!", user: "hilda" },
  { message: "I'm going to become the Champion!", user: "hilbert" },
  { message: "My Samurott is so powerful!", user: "hilda" },
  { message: "Emboar, use Flare Blitz!", user: "hilbert" },
  { message: "Serperior, use Leaf Storm!", user: "hilda" },
  { message: "My team is ready for anything!", user: "hilbert" },
  { message: "I'm catching all the Unova Pokémon!", user: "hilda" },
  { message: "Exploring the Giant Chasm!", user: "hilbert" },
  { message: "Battling legendary Pokémon!", user: "hilda" },
  { message: "Unraveling the mysteries of Unova!", user: "hilbert" },
  { message: "Making new friends on my journey!", user: "hilda" },
  { message: "My Pokémon are my best friends!", user: "hilbert" },
  { message: "I'm having so much fun on my adventure!", user: "hilda" },
  { message: "I'll never give up on my dreams!", user: "hilbert" },
  { message: "I'm going to become the very best!", user: "hilda" },
  { message: "Nothing can stop me!", user: "hilbert" },
  { message: "I'm living my best life!", user: "hilda" },
  { message: "This is my story!", user: "hilbert" },
  { message: "My journey continues!", user: "hilda" },
  { message: "Go, Darumaka! Time to heat things up!", user: "darumaka_fan" },
  {
    message: "Watch out, my Krookodile is ready to chomp!",
    user: "krookodile_trainer",
  },
  { message: "My Lilligant is blooming beautifully!", user: "liiligant_lover" },
  { message: "Scolipede, use Poison Jab!", user: "scolipede_master" },
  {
    message: "My Excadrill is digging its way to victory!",
    user: "excadrill_ace",
  },
  { message: "Archeops, use Acrobatics!", user: "archeops_pilot" },
  { message: "My Chandelure's flames will burn you!", user: "chandelure_user" },
  { message: "Haxorus, Dragon Claw!", user: "haxorus_trainer" },
  {
    message: "My Hydreigon is a three-headed terror!",
    user: "hydreigon_master",
  },
  { message: "Volcarona, Fiery Dance!", user: "volcarona_dancer" },
  { message: "Team Plasma's ideals are twisted!", user: "plasma_opponent" },
  { message: "N, you're wrong about Pokémon!", user: "n_challenger" },
  { message: "Ghetsis, your plans will fail!", user: "ghetsis_rival" },
  {
    message: "We must protect Pokémon from Team Plasma!",
    user: "pokemon_protector",
  },
  { message: "The future of Pokémon is at stake!", user: "future_guardian" },
  { message: "Elesa's fashion sense is electrifying!", user: "elesa_fan" },
  { message: "Clay's ground-type Pokémon are tough!", user: "clay_challenger" },
  { message: "Skyla's air battles are a thrill!", user: "skyla_admirer" },
  { message: "Brycen's ice types are chilling!", user: "brycen_opponent" },
  {
    message: "Drayden's dragon Pokémon are legendary!",
    user: "drayden_disciple",
  },
  { message: "Iris's champion spirit is inspiring!", user: "iris_supporter" },
  { message: "Exploring the vast deserts of Unova!", user: "desert_explorer" },
  { message: "Surfing the waves of Undella Bay!", user: "undella_surfer" },
  {
    message: "Climbing the twisting paths of Twist Mountain!",
    user: "twist_mountain_climber",
  },
  {
    message: "Discovering the secrets of the Relic Castle!",
    user: "relic_castle_archaeologist",
  },
  { message: "Lost in the Pinwheel Forest!", user: "lost_in_the_woods" },
  {
    message: "Searching for rare berries in the Dream World!",
    user: "dream_world_berry_hunter",
  },
  {
    message: "Training my Pokémon in the Entralink!",
    user: "entralink_trainer",
  },
  {
    message: "Participating in the Pokémon World Tournament!",
    user: "pwt_competitor",
  },
  {
    message: "Battling against legendary trainers from other regions!",
    user: "legendary_trainer_battler",
  },
  { message: "My Pokémon are my family!", user: "pokemon_family" },
  {
    message: "I'm on a journey of self-discovery!",
    user: "self_discovery_trainer",
  },
  {
    message: "I'm learning the true meaning of friendship!",
    user: "friendship_trainer",
  },
  {
    message: "I'm making memories that will last a lifetime!",
    user: "memory_maker",
  },
  { message: "My Popplio is learning a new Z-Move!", user: "popplio_trainer" },
  { message: "Litten, use Fire Blast!", user: "litten_fan" },
  { message: "Rowlet, use Leafage!", user: "rowlet_lover" },
  { message: "Exploring Melemele Island!", user: "island_explorer" },
  { message: "Challenging the Island Kahuna!", user: "kahuna_challenger" },
  {
    message: "Participating in the Alola Pokémon League!",
    user: "alola_league_competitor",
  },
  { message: "Battling Ultra Beasts!", user: "ultra_beast_hunter" },
  { message: "Meeting the Tapu Guardians!", user: "tapu_seeker" },
  { message: "My Incineroar is unstoppable!", user: "incineroar_master" },
  { message: "Primarina's singing is enchanting!", user: "primarina_admirer" },
  {
    message: "Decidueye's arrows are precise!",
    user: "decidueye_sharpshooter",
  },
  { message: "Alola is such a beautiful region!", user: "alola_tourist" },
  { message: "Making new friends in Alola!", user: "alola_friend" },
  { message: "Experiencing the Alolan culture!", user: "culture_enthusiast" },
  {
    message: "Learning the ways of the Island Challenge!",
    user: "island_challenge_trainee",
  },
  { message: "Protecting Alola from danger!", user: "alola_protector" },
  { message: "My Pokémon and I are a strong team!", user: "alola_team" },
  { message: "I'm becoming a true Pokémon trainer!", user: "alola_trainer" },
  { message: "The Alolan sunshine is so warm!", user: "sun_lover" },
  { message: "Riding the waves in Alola!", user: "wave_rider" },
  { message: "Exploring the lush forests of Alola!", user: "forest_wanderer" },
  {
    message: "Discovering the secrets of Alola's ruins!",
    user: "ruin_explorer_alola",
  },
  { message: "My Grookey is so energetic!", user: "grookey_pal" },
  { message: "Scorbunny, use Double Kick!", user: "scorbunny_trainer" },
  { message: "Sobble, use Water Gun!", user: "sobble_friend" },
  { message: "Exploring the Galar region!", user: "galar_explorer" },
  {
    message: "Challenging the Galar Gym Leaders!",
    user: "gym_challenger_galar",
  },
  {
    message: "Participating in the Galar Pokémon League!",
    user: "galar_league_participant",
  },
  { message: "Dynamaxing my Pokémon!", user: "dynamax_master" },
  { message: "Gigantamaxing my Pokémon!", user: "gigantamax_champion" },
  { message: "Battling in the Champion Cup!", user: "champion_cup_competitor" },
  {
    message: "Meeting the legendary Pokémon of Galar!",
    user: "galar_legend_seeker",
  },
  { message: "My Rillaboom's drumming is powerful!", user: "rillaboom_rocker" },
  { message: "Cinderace's kicks are fiery!", user: "cinderace_striker" },
  { message: "Inteleon's sniping is precise!", user: "inteleon_agent" },
  { message: "Galar is such a vibrant region!", user: "galar_enthusiast" },
  { message: "Making new friends in Galar!", user: "galar_buddy" },
  { message: "Experiencing the Galarian culture!", user: "galar_culture_buff" },
  {
    message: "Training my Pokémon in the Wild Area!",
    user: "wild_area_trainer",
  },
  {
    message: "Catching rare Pokémon in Max Raid Battles!",
    user: "max_raid_battler",
  },
  { message: "Cooking delicious curry with my Pokémon!", user: "curry_chef" },
  { message: "Camping with my Pokémon!", user: "pokemon_camper" },
  {
    message: "Becoming the strongest trainer in Galar!",
    user: "galar_champion_hopeful",
  },
  { message: "The Galarian spirit is so inspiring!", user: "galar_spirit_fan" },
  { message: "Exploring the Crown Tundra!", user: "crown_tundra_adventurer" },
  {
    message: "Discovering the secrets of the Isle of Armor!",
    user: "isle_of_armor_explorer",
  },
] as CharacterMessage[];
